#!/bin/bash

set -e

SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
WORKING_DIR="$( pwd )"

cd "$SCRIPT_DIR/ArtificialIntelligence"

# Escape params (doh, sbt!)
declare -a params
last_param=
for i in $(seq 1 $#); do
  if [[ "x$last_param" = "x-f" ]]; then
    params[$i]="$( echo "$WORKING_DIR/${!i}" | sed 's/ /\\ /' )"
  else
    params[$i]="$( echo "${!i}" | sed 's/ /\\ /' )"
  fi
  last_param="${!i}"
done

exec sbt "run-main Main ${params[*]}"
